// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqw7sTnT6xIh63LUZyQy4yY7quOkaunaE',
    appId: '1:424849999892:ios:3c5d022ec173f5d67ebf01',
    messagingSenderId: '424849999892',
    projectId: 'fatecinternship',
    storageBucket: 'fatecinternship.appspot.com',
    iosBundleId: 'com.example.fatecInternship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApVez6vibMNhmxF0mwzt732Fro7IueaTU',
    appId: '1:424849999892:web:b402b474765c800d7ebf01',
    messagingSenderId: '424849999892',
    projectId: 'fatecinternship',
    authDomain: 'fatecinternship.firebaseapp.com',
    storageBucket: 'fatecinternship.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApVez6vibMNhmxF0mwzt732Fro7IueaTU',
    appId: '1:424849999892:web:b402b474765c800d7ebf01',
    messagingSenderId: '424849999892',
    projectId: 'fatecinternship',
    authDomain: 'fatecinternship.firebaseapp.com',
    storageBucket: 'fatecinternship.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqw7sTnT6xIh63LUZyQy4yY7quOkaunaE',
    appId: '1:424849999892:ios:3c5d022ec173f5d67ebf01',
    messagingSenderId: '424849999892',
    projectId: 'fatecinternship',
    storageBucket: 'fatecinternship.appspot.com',
    iosBundleId: 'com.example.fatecInternship',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3GIf39e5eQj0EHedmFdnL-QBWqJzNM6w',
    appId: '1:424849999892:android:13ff7150fdb1391c7ebf01',
    messagingSenderId: '424849999892',
    projectId: 'fatecinternship',
    storageBucket: 'fatecinternship.appspot.com',
  );

}